env:
  node: true
  es6: true
plugins:
  - unicorn
extends:
  - "@sidy/eslint-config-sidy"
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: babel-eslint # to use optional chaining and other cool stuff
parserOptions:
  ecmaVersion: 2020
  sourceType: module