language: node_js
node_js:
  - node
script:
  - npm run test
  - npm run build
deploy:
  provider: npm
  email: '$NPM_EMAIL'
  api_key: '$NPM_TOKEN'
  skip_cleanup: true
  script: echo "Deploying to npm ..."
  on:
    tags: true
    branch: master
